eureka:
  client:
    instance:
      hostname: localhost
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: caches
    health:
      show-details: always