spring:
  application:
    name: product-service-prod

  dataSource:
    url: jdbc:mysql://localhost:3306/proddb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 2020