spring:
  application:
    name: product-service-qa

  dataSource:
    url: jdbc:mysql://localhost:3306/qadb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9091