server:
  port: 8086
  servlet:
    context-path: /restuarant

spring:
  application:
    name: restuarant-service-dev
  datasource:
    url: jdbc:mysql://localhost:3306/harsha_mart
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update